jobtracker/jobtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tracker/', include('tracker.urls', namespace='tracker')),
    path('offer/', include('offer.urls', namespace="offer")),
    path('', views.IndexView.as_view(), name="index"),
]

jobtracker/offer/urls.py
from django.urls import path
from . import views

app_name = 'offer'

urlpatterns = [
    path('<tracker_id>/list/', views.OfferListView.as_view(), name='offer_list'), 
    path('<tracker_id>/list/refresh/', views.OfferListRefresh.as_view(), name='refresh'),
]

jobtracker/offer/models.py
from django.db import models
from tracker.models import Tracker
from .fields import OrderField
# Create your models here.


class Offer(models.Model):
    foreign_identity = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    snippet = models.TextField(null=True, blank=True)
    salary = models.CharField(max_length=50, null=True, blank=True)
    source = models.CharField(max_length=100, blank=True, null=True)
    job_type = models.CharField(max_length=150, blank=True, null=True)
    link = models.URLField(max_length=350)
    company = models.CharField(max_length=150, null=True, blank=True)
    updated = models.DateTimeField()
    order = OrderField(blank=True, for_fields=['owner'])
    owner = models.ForeignKey(Tracker,
                       related_name='offers', 
                       on_delete=models.CASCADE, 
                       null=True, blank=True)

    class Meta:
        ordering = ['-order']

    def __str__(self):
        return self.title

jobtracker/offer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Offer
from tracker.models import Tracker
from django.views import View
from django.views.generic.list import ListView
from braces.views import LoginRequiredMixin
from tracker.tasks import update_jobs
import requests

# Create your views here.

""" Displays list of Offer objects belonging to one Tracker instance """

class OfferListView(LoginRequiredMixin, View):
    def get(self, request, tracker_id):
        tracker = get_object_or_404(Tracker, id=tracker_id)
        offers = Offer.objects.filter(owner=tracker)

        context = {'offers': offers, 'tracker': tracker}

        return render(request, 'offer/list.html', context)

""" Updates offers belonging to one Tracker instance and refreshes current site """

class OfferListRefresh(LoginRequiredMixin, View):
    def get(self, request, tracker_id):
        tracker = get_object_or_404(Tracker, id=tracker_id)
        update_jobs.delay(tracker.id)
        return redirect('offer:offer_list', tracker_id)

jobtracker/offer/templates/offer/detail.html
Działa

jobtracker/offer/templates/offer/list.html
{% extends 'base.html' %}

{% block title %} Ogłoszenia {% endblock %}

{% block content %}
    <a href="{% url 'offer:refresh' tracker.id %}"><h2>Refresh</h2></a>
    {% if offers %}
        {% for offer in offers %}
            <div class="offer_container">
                <div class="title">
                    <a href="{{ offer.link }}"><h3>{{ offer.title }}</h3></a>
                </div>
                <div class="location">
                    <p><b>Lokalizacja:</b> {{ offer.location }}</p>
                </div>
                <div class="salary">
                    <p><b>Stawka:</b> {{ offer.salary }} PLN</p>
                </div>

                    <div class="snippet">
                        <p>
                            <b>Opis:</b> 
                            {% autoescape off %}
                                {{ offer.snippet|truncatechars:300 }}
                            {% endautoescape %}
                        </p>
                    </div>
                <div class="link">
                    <p><b>Link:</b> <a href="{{ offer.link }}">Przejdź do oferty</a></p>
                </div>
            </div>
        {% endfor %}
    {% else %}
            <h1>Nie znaleziono jeszcze żadnych ofert spełniających podane kryteria</h1>
    {% endif %}
{% endblock %}