jobtracker/accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth
from . import views

urlpatterns = [
    path('register/', views.AccountRegisterView.as_view(), name='register'),
    path('login/', auth.LoginView.as_view(), name='login'),
    path('logout/', auth.LogoutView.as_view(), name='logout'),
    path('password-change/', auth.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done', auth.PasswordChangeDoneView.as_view(),
        name='password_change_done'),
    path('edit/', views.UserEditView.as_view(), name='edit'),
    path('', views.DashboardView.as_view(), name='dashboard'),
]

jobtracker/jobtracker/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tracker/', include('tracker.urls', namespace='tracker')),
    path('offer/', include('offer.urls', namespace="offer")),
    path('', views.IndexView.as_view(), name="index"),
]

jobtracker/offer/urls.py
from django.urls import path
from . import views

app_name = 'offer'

urlpatterns = [
    path('<tracker_id>/list/', views.OfferListView.as_view(), name='offer_list'), 
    path('<tracker_id>/list/refresh/', views.OfferListRefresh.as_view(), name='refresh'),
]

jobtracker/tracker/urls.py
from django.urls import path
from . import views


app_name = 'trakcer'

urlpatterns = [
    path('<int:tracker_id>/', views.TrackerEditView.as_view(), name='tracker_detail'),
    path('create/', views.TrackerCreateView.as_view(), name='create'),
    path('delete/<tracker_id>/', views.TrackerDeleteView.as_view(), name='delete'),
    
]

jobtracker/accounts/models.py
from django.db import models

# Create your models here.

jobtracker/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

jobtracker/accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views import View
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy
from .forms import UserEditForm
from braces.views import LoginRequiredMixin
from tracker.models import Tracker
from django.views.generic.list import ListView
# Create your views here.

""" Index view redirects unauthenticated users to login site
    and authenticated to dashboard """

class IndexView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('dashboard')
        else:
            return redirect('login')

""" Registration view """

class AccountRegisterView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = form.save()
        login(self.request, user)
        return result

""" Dashboard view, implicitly diplays list of Tracker objects
    belonging to current user """

class DashboardView(LoginRequiredMixin, ListView):
    model = Tracker
    paginate_by = 5
    template_name = 'account/tracker/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)


""" User edit view """

class UserEditView(View, LoginRequiredMixin):
    def get(self, request):
        form = UserEditForm(instance = request.user)
        return render(request, 'account/edit.html', {'form': form})

    def post(self, request):
        form = UserEditForm(instance=request.user, data=request.POST)
        
        if form.is_valid():
            form.save()
        return redirect('dashboard')

jobtracker/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <a href="/" class="logo">JobTracker</a>
            <ul class="menu">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Wyloguj</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Zaloguj</a></li>
                {% endif %}
            </ul>
        </div>
        <div id="content">
        {% if request.user.is_authenticated %}
                <div class="sidenav">
                    <a href="{% url 'dashboard' %}" class="nav_item"><div>Trackery</div></a>
                    <a href="{% url 'edit' %}" class="nav_item"><div>Edytuj profil</div></a>
                    <a href="{% url 'tracker:create' %}" class="nav_item"><div>Dodaj tracker</div></a>
                </div>
        {% endif %}
        {% block content %}
        {% endblock %}
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

        <script>
            $(document).ready(function(){
                {% block domready %}
                {% endblock %}
            });
        </script>
    </body>
</html>